on:
  schedule:
    - cron:  '*/5 * * * *'
name: Update schedule
jobs:
  build:
    name:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Setup Go
          uses: actions/setup-go@master
          with:
            go-version: '1.20'
        - name: Build
          run: go build -v ./...
        - name: Test
          run: go test -v ./...
        - name: Run
          run: go run main.go
        - uses: mikeal/publish-to-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}